Git Actions CI template on nestjs template
poviolabs/ecs-deploy-cli pull request #7
Opened 2022-06-28 08:22 UTC by itstriolink

2022-06-28 11:24 UTC, adrianjarc requested changes

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +        uses: actions/checkout@v2.1.0
Could we use newest GH action `actions/checkout@v3`?

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +        uses: actions/setup-node@v2
Could we use newest GH action `actions/setup-node@v3`?

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          node-version: 14
Wouldn't exactly fixate a node version here. Since it is a template I would propose that this is set per project.

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +      - name: Cache Dependencies
I think this step can be skipped if we use newer GH action for node setup with argument: `cache: yarn`

example:
```
- name Install NodeJS
  uses: actions/setup-node@v3
  with:
    cache: yarn
```

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +        run: yarn add slack-notify-cli@poviolabs/slack-notify-cli#v1
Could this be 1 step?

```
- name: Install cli tools
  run: yarn add ecs-deploy-cli@poviolabs/ecs-deploy-cli#v2 slack-notify-cli@poviolabs/slack-notify-cli#v1
```

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
Since there have been changes made with previous commands this command will most probably fail, because there are changes in git.

2022-06-28 11:24 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          BUILD_URL=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
In my tests this argument seems to not have any effect on end message

2022-06-28 11:32 UTC, itstriolink commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          BUILD_URL=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
Which argument? `BUILD_URL` ?

2022-06-28 11:32 UTC, itstriolink commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
Because of which ENV variable? What part exactly will fail here?

2022-06-28 11:37 UTC, itstriolink commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
I don't think it will fail, I tested this out.

There won't be any changes since both of the CLI packages are already included in the `package.json` file.

2022-06-28 11:38 UTC, itstriolink commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          BUILD_URL=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
BUILD_URL acts as a link to the Github action itself and APP_VERSION acts as a placeholder for that link i.e. referring to the branch that the job was run on.

2022-06-28 11:42 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
Well only if they are included in package.json. On my project they aren't, and they can't be, until yarn is not updated.

2022-06-28 11:43 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
> Because of which ENV variable? What part exactly will fail here?

No env variable. Previous commands of installing packages changes git repo if those tools are not in package.json already.

2022-06-28 11:45 UTC, itstriolink commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
We are using yarn, it is only installing the necessary tools (`ecs-deploy-cli` and `slack-notify-cli`), unless I am missing something?

2022-06-28 11:48 UTC, itstriolink commented
@adrianjarc Here's an example of the GIT workflow in action with the requested changes (working fine):
https://github.com/poviolabs/bug-reporting-be/runs/7091772961?check_suite_focus=true

2022-06-28 11:52 UTC, MarZab commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
Yes. You cant use yarn v1 and its a requirement for some projects. Lets go with 'npm' global onstall so we dont need the packages in package.json

2022-06-28 11:54 UTC, adrianjarc commented
> @adrianjarc Here's an example of the GIT workflow in action with the requested changes (working fine): https://github.com/poviolabs/bug-reporting-be/runs/7091772961?check_suite_focus=true

I do not have access to this repo. So I can not see it. I believe you. But on some older projects, this is failing. My project initially failed because of the yarn version and later because of git changes.

2022-06-28 11:57 UTC, adrianjarc commented on examples/nestjs/.github/workflows/ecs-deploy.yml
> +          yarn ecs-deploy-cli build
Yes, you are missing that we are also moving legacy projects on this, and not all use yarn. And many projects are still on yarn 1. Those templates are to be made as simple as possible for most to understand and use.

2022-06-28 12:53 UTC, itstriolink commented
The comments have been resolved, let me know if there's anything else you want to add.

@adrianjarc

2022-06-29 03:42 UTC, adrianjarc approved these changes

2022-06-29 06:02 UTC, MarZab approved these changes

2022-06-29 06:02 UTC, merged